[package]
name = "SwapEbr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[dev-dependencies]
rand = "0.8"
arc-swap = "1.5.1"
criterion = "0.5.1"
swap-arc = "0.1.1"

[[bench]]
name = "swap_arc"
harness = false