[package]
name = "SwapEbr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# default = ["no_std"]
no_std = []

[dependencies]


[dev-dependencies]
rand = "0.8"
arc-swap = "1.7"
criterion = "0.5.1"
swap-arc = "0.1.1"
aarc = "0.1"

[[bench]]
name = "swap_ebr"
harness = false